# Generated by Django 3.0.1 on 2020-01-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200126_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskimage',
            name='image',
            field=models.ImageField(default='../assets/devices/computer.svg', upload_to=''),
        ),
    ]
