# Generated by Django 3.0.1 on 2020-02-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_virtualmachine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='cell_id',
            field=models.IntegerField(default='0'),
        ),
    ]
