# Generated by Django 3.0.1 on 2020-02-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_diskimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diskimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='diskimage',
            name='devicetype',
            field=models.CharField(choices=[('router', 'router'), ('pc', 'pc'), ('switch', 'switch'), ('mlswitch', 'multi-layer switch'), ('server', 'server')], default='pc', max_length=8),
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=8)),
                ('disk_size', models.IntegerField()),
                ('cpus', models.IntegerField()),
                ('disk_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.DiskImage')),
            ],
        ),
    ]
