# Generated by Django 3.0.1 on 2020-02-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_virtualmachine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(default='vm_name', max_length=100),
        ),
    ]
