# Generated by Django 3.0.1 on 2020-02-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_virtualmachine_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(default='vm_name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='token',
            field=models.CharField(default='osE2OMDFCFhIbw-kEfKU3g', max_length=22),
        ),
    ]
