# Generated by Django 3.0.1 on 2020-02-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200227_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(default='vm_name', error_messages={'unique': 'A device with this name already exists.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='token',
            field=models.CharField(default='9qEE-9WodooZZgP2yicsXw', max_length=22),
        ),
    ]
