# Generated by Django 3.0.1 on 2020-02-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200227_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(default='vm_name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='token',
            field=models.CharField(default='a6ea6d25-ca45-411c-bd55-24306dd393c3', max_length=64),
        ),
    ]
