# Generated by Django 3.0.1 on 2020-02-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200229_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='token',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
