# Generated by Django 3.0.1 on 2020-03-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200229_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthernetPorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_to', models.CharField(max_length=10)),
                ('virtual_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.VirtualMachine')),
            ],
        ),
    ]
