# Generated by Django 3.0.1 on 2020-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_ethernetports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskimage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
