# Generated by Django 3.0.1 on 2020-03-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200311_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethernetports',
            name='port_no',
            field=models.IntegerField(default=0),
        ),
    ]
