# Generated by Django 3.0.1 on 2020-04-03 00:26

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('home', '0018_auto_20200402_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EthernetPorts',
            new_name='EthernetPort',
        ),
    ]
