# Generated by Django 3.0.1 on 2020-04-03 00:32

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('home', '0019_auto_20200403_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EthernetPort',
            new_name='EthernetPorts',
        ),
    ]
