# Generated by Django 3.0.1 on 2020-04-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20200403_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethernetcable',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source', to='home.EthernetPorts'),
        ),
        migrations.AlterField(
            model_name='ethernetcable',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target', to='home.EthernetPorts'),
        ),
    ]
