# Generated by Django 3.0.1 on 2020-04-13 21:56

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0023_auto_20200403_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VirtualMachine',
            new_name='Device',
        ),
    ]
