# Generated by Django 3.0.1 on 2020-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200413_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='console_port',
            field=models.IntegerField(default='10000'),
        ),
    ]
