# Generated by Django 3.0.1 on 2020-05-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_device_console_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='disk_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.DiskImage'),
        ),
    ]
